In [478]:
import pandas as pd
import json
import os
import psycopg2

In [479]:
df_new = pd.read_csv("/Applications/python/nutristeppe/data/type3_with_cat2.csv")
df_new

,bls_code,new_name,dish_category_code,type,type_5
0,B780200,Steiofebrot хлеб запеченный на каменных плитах,DGH0101,3,5
1,F201000,Абрикос,FR,3,1
2,F201100,Абрикос сырой,FR,3,5
3,F201101,Абрикос цельный,FR,3,5
4,F028700,Абрикосово-апельсиновый нектар,BEV04,3,4
...,...,...,...,...,...
5813,E108122,Яйцо пашот белок,EGG,2,5
5814,31105020,"Яйцо, жареное с маргарином",EGG,2,4
5815,17-743,Ячменная вода,BEV04,3,5
5816,51801010,Ячменный хлеб,DGH0102,3,2
5817,B241000,Ячменный черный хлеб,DGH0101,3,5

In [480]:
df_new = df_new.rename(columns={"new_name": "name", "type_5": "availability_type"})
df_new

,bls_code,name,dish_category_code,type,availability_type
0,B780200,Steiofebrot хлеб запеченный на каменных плитах,DGH0101,3,5
1,F201000,Абрикос,FR,3,1
2,F201100,Абрикос сырой,FR,3,5
3,F201101,Абрикос цельный,FR,3,5
4,F028700,Абрикосово-апельсиновый нектар,BEV04,3,4
...,...,...,...,...,...
5813,E108122,Яйцо пашот белок,EGG,2,5
5814,31105020,"Яйцо, жареное с маргарином",EGG,2,4
5815,17-743,Ячменная вода,BEV04,3,5
5816,51801010,Ячменный хлеб,DGH0102,3,2
5817,B241000,Ячменный черный хлеб,DGH0101,3,5

In [481]:
df_new[df_new['bls_code'] == 'M306400']

,bls_code,name,dish_category_code,type,availability_type
4850,M306400,Сыр Пармезан 30% жирности,CH01,3,1

In [482]:
df_old = pd.read_csv("/Applications/python/nutristeppe/data/19March.csv")
df_old

,Unnamed: 0,bls_code,dish_category_id,dish_category_code,kilocalories,protein,fat,carbohydrate,cfv,fvnl,...,serving_method,quality_requirements,ingredients,techcard,fiber,sugar_mg,salt_total_mg,saturated_fat_mg,pfs_unit,serving_size_g
0,0,X659012,5.0,GAR0201,100.0,0.000,0.000,0.000,0.0,100.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg,100.0
1,1,Y504322,7.0,MT01,141.0,0.000,0.000,0.000,0.0,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg,90.0
2,2,X880522,6.0,GAR0202,115.0,0.000,0.000,0.000,16.7,30.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg,100.0
3,3,X693213,41.0,EGG,131.0,0.000,0.000,0.000,0.0,33.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg,140.0
4,4,X468713,29.0,CMT02,96.0,0.000,0.000,0.000,0.0,16.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg,150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6086,6086,Y891312,16.0,DGH0201,194.9,5.619,7.842,25.460,0.0,30.00,...,"Подают горячими, можно посыпать сахаром или по...","Блины должны быть золотистого цвета, мягкие и ...","['мука', 'яйцо', 'молоко', 'яблоко', 'сахар', ...","Муку смешивают с сахаром и солью, отдельно взб...",0.845,8.563,0.394,1.771,g,100.0
6087,6087,Y891433,38.0,CC,188.6,6.988,7.467,23.350,0.0,0.00,...,"Подают горячими, можно добавить свежие фрукты.","Блинчики должны быть золотистого цвета, мягкие...","['мука', 'яйцо', 'молоко', 'творог', 'соль', '...","В глубокой миске смешать муку, яйца, молоко и ...",0.604,7.466,0.274,2.559,g,100.0
6088,6088,Y892142,3.0,GAR0103,178.5,5.280,0.805,37.540,26.3,26.30,...,"Подают горячими, можно посыпать сахаром или по...","Внешний вид: клецки одинаковой формы, без трещ...","['картофель', 'мука', 'сахар', 'соль', 'яйцо']","Картофель отварить до полной готовности, воду ...",1.660,3.734,0.320,0.215,g,100.0
6089,6089,Y912130,10.0,MT04,123.9,10.480,5.848,7.347,200.0,600.00,...,"Блюдо подают горячим, температура подачи 65-70°C.","Котлета должна быть золотистой, с хрустящей ко...","['говядина', 'картофель', 'лук репчатый', 'гор...",Для приготовления котлеты говядину пропускаем ...,0.641,0.596,0.341,0.684,g,90.0
6090,6090,Y921062,29.0,CMT02,225.8,11.150,7.562,28.280,0.0,50.00,...,"Подается горячей, порционирование по 100 грамм.","Внешний вид: аппетитная, золотистая корочка мя...","['питта', 'телятина', 'говядина', 'салат', 'ма...",1. Подготовить ингредиенты: нарезать телятину ...,1.284,0.971,0.333,0.836,g,150.0

In [483]:
df_old[df_old['bls_code'] == 'M306400']

Empty DataFrame
Columns: [Unnamed: 0, bls_code, dish_category_id, dish_category_code, kilocalories, protein, fat, carbohydrate, cfv, fvnl, index_health, type, availability_type, name, steps, serving_method, quality_requirements, ingredients, techcard, fiber, sugar_mg, salt_total_mg, saturated_fat_mg, pfs_unit, serving_size_g]
Index: []

[0 rows x 25 columns]

In [484]:
df_old.columns

Index(['Unnamed: 0', 'bls_code', 'dish_category_id', 'dish_category_code',
       'kilocalories', 'protein', 'fat', 'carbohydrate', 'cfv', 'fvnl',
       'index_health', 'type', 'availability_type', 'name', 'steps',
       'serving_method', 'quality_requirements', 'ingredients', 'techcard',
       'fiber', 'sugar_mg', 'salt_total_mg', 'saturated_fat_mg', 'pfs_unit',
       'serving_size_g'],
      dtype='object')

In [485]:
# 1. Делаем bls_code индексом в обоих таблицах
df_old.set_index('bls_code', inplace=True)
df_new.set_index('bls_code', inplace=True)

# 2. Обновляем старые данные новыми
# ВАЖНО: update изменяет df_old прямо на месте (inplace)
df_old.update(df_new)

# 3. Возвращаем индекс в колонку, если нужно
df_final = df_old.reset_index()

# 4. Если в df_new были СОВЕРШЕННО НОВЫЕ строки (которых не было в old), 
# их нужно добавить через combine_first или concat
df_final = df_new.combine_first(df_old).reset_index()

In [486]:
df_final

,bls_code,Unnamed: 0,availability_type,carbohydrate,cfv,dish_category_code,dish_category_id,fat,fiber,fvnl,...,protein,quality_requirements,salt_total_mg,saturated_fat_mg,serving_method,serving_size_g,steps,sugar_mg,techcard,type
0,11-1000,5491.0,2.0,0.00,0.0,VEG01,58.0,0.000,NaN,0.0,...,0.000,NaN,NaN,NaN,NaN,250.0,NaN,NaN,NaN,2.0
1,11-1003,NaN,5.0,NaN,NaN,DGH0102,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
2,11-1006,166.0,1.0,53.16,0.0,DGH0201,16.0,3.709,2.505,0.0,...,7.905,"Булочки должны быть мягкими, с золотистой коро...",0.303,0.301,"Подавать теплые, при температуре 60-70°C.",100.0,"Смешать муку, сахар, соль и дрожжи. Постепенно...",3.61,"Смешать муку, сахар, соль и дрожжи. Постепенно...",2.0
3,11-1011,5369.0,2.0,0.00,0.0,DGH05,20.0,0.000,NaN,0.0,...,0.000,NaN,NaN,NaN,NaN,250.0,NaN,NaN,NaN,2.0
4,11-1012,1728.0,2.0,32.64,0.0,DGH05,20.0,3.340,NaN,0.0,...,10.170,"Внешний вид: золотистая корочка, равномерно ра...",NaN,NaN,"Пиццу подают горячей, нарезанной на порционные...",250.0,Пшеничную муку смешивают с сухими дрожжами и ч...,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11377,Y995140,2833.0,1.0,20.04,0.0,DES02,40.0,0.232,2.240,0.0,...,0.406,"Внешний вид: золотистая корочка, дольки мягкие...",0.002,0.031,Подают теплой с шариком ванильного мороженого ...,90.0,Помыть и очистить груши от кожуры. Разрезать п...,18.35,Помыть и очистить груши от кожуры. Разрезать п...,2.0
11378,Y996000,NaN,5.0,NaN,NaN,DES02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
11379,Y999140,NaN,4.0,NaN,NaN,DES02,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
11380,Y999242,4411.0,2.0,0.00,0.0,DES02,40.0,0.000,NaN,20.0,...,0.000,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,2.0
11381,n420100,2504.0,2.0,0.00,0.0,BEV07,27.0,0.000,NaN,0.0,...,0.000,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,2.0

In [487]:
df_final.columns

Index(['bls_code', 'Unnamed: 0', 'availability_type', 'carbohydrate', 'cfv',
       'dish_category_code', 'dish_category_id', 'fat', 'fiber', 'fvnl',
       'index_health', 'ingredients', 'kilocalories', 'name', 'pfs_unit',
       'protein', 'quality_requirements', 'salt_total_mg', 'saturated_fat_mg',
       'serving_method', 'serving_size_g', 'steps', 'sugar_mg', 'techcard',
       'type'],
      dtype='object')

In [488]:
# Находим индексы строк, которые нужно удалить
# Условие: type == 1 И type_5 входит в список [3, 4, 5]
to_drop = df_final[(df_final['type'] == 1) | (df_final['availability_type'].isin([3, 4, 5]))].index

# Удаляем эти строки
df_final = df_final.drop(to_drop)
df_final=df_final.drop(columns=['Unnamed: 0'])
df_final

,bls_code,availability_type,carbohydrate,cfv,dish_category_code,dish_category_id,fat,fiber,fvnl,index_health,...,protein,quality_requirements,salt_total_mg,saturated_fat_mg,serving_method,serving_size_g,steps,sugar_mg,techcard,type
0,11-1000,2.0,0.00,0.0,VEG01,58.0,0.000,NaN,0.0,0.00,...,0.000,NaN,NaN,NaN,NaN,250.0,NaN,NaN,NaN,2.0
2,11-1006,1.0,53.16,0.0,DGH0201,16.0,3.709,2.505,0.0,0.00,...,7.905,"Булочки должны быть мягкими, с золотистой коро...",0.303,0.301,"Подавать теплые, при температуре 60-70°C.",100.0,"Смешать муку, сахар, соль и дрожжи. Постепенно...",3.61,"Смешать муку, сахар, соль и дрожжи. Постепенно...",2.0
3,11-1011,2.0,0.00,0.0,DGH05,20.0,0.000,NaN,0.0,0.00,...,0.000,NaN,NaN,NaN,NaN,250.0,NaN,NaN,NaN,2.0
4,11-1012,2.0,32.64,0.0,DGH05,20.0,3.340,NaN,0.0,0.00,...,10.170,"Внешний вид: золотистая корочка, равномерно ра...",NaN,NaN,"Пиццу подают горячей, нарезанной на порционные...",250.0,Пшеничную муку смешивают с сухими дрожжами и ч...,NaN,NaN,2.0
5,11-1013,2.0,0.00,0.0,DGH05,20.0,0.000,NaN,0.0,0.00,...,0.000,NaN,NaN,NaN,NaN,250.0,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11374,Y993340,2.0,0.00,0.0,DES02,40.0,0.000,NaN,0.0,0.00,...,0.000,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,2.0
11375,Y993440,2.0,0.00,0.0,DES02,40.0,0.000,NaN,19.2,0.25,...,0.000,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,2.0
11377,Y995140,1.0,20.04,0.0,DES02,40.0,0.232,2.240,0.0,2.50,...,0.406,"Внешний вид: золотистая корочка, дольки мягкие...",0.002,0.031,Подают теплой с шариком ванильного мороженого ...,90.0,Помыть и очистить груши от кожуры. Разрезать п...,18.35,Помыть и очистить груши от кожуры. Разрезать п...,2.0
11380,Y999242,2.0,0.00,0.0,DES02,40.0,0.000,NaN,20.0,0.75,...,0.000,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,2.0
11381,n420100,2.0,0.00,0.0,BEV07,27.0,0.000,NaN,0.0,3.50,...,0.000,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,2.0

In [489]:
df_final.describe()

,availability_type,carbohydrate,cfv,dish_category_id,fat,fiber,fvnl,index_health,kilocalories,protein,salt_total_mg,saturated_fat_mg,serving_size_g,sugar_mg,type
count,6174.000000,5712.000000,5712.000000,5687.000000,5712.000000,2600.000000,5712.000000,5712.000000,5712.000000,5712.00000,2600.000000,2600.000000,5687.000000,2600.000000,6174.000000
mean,1.465339,9.871409,21.813136,30.152629,3.877566,1.642809,46.591999,2.148372,174.583365,5.23946,0.355501,2.173399,143.039388,2.528415,2.067865
std,0.498838,16.612462,89.181991,17.613675,6.196296,2.011847,133.439805,1.656127,109.648762,6.32655,0.280308,2.770288,63.306060,3.863552,0.251535
min,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,10.000000,0.000000,2.000000
25%,1.000000,0.000000,0.000000,16.000000,0.000000,0.368000,0.000000,0.000000,92.762500,0.00000,0.301000,0.364750,100.000000,0.644750,2.000000
50%,1.000000,0.672000,0.000000,29.000000,0.960500,1.144000,3.000000,2.250000,153.800000,1.89450,0.333000,1.022000,150.000000,1.284000,2.000000
75%,2.000000,11.682500,2.500000,48.000000,5.700000,2.092500,45.500000,3.500000,241.825000,9.37800,0.402000,2.948500,200.000000,2.564250,2.000000
max,2.000000,85.110000,1800.000000,62.000000,93.840000,22.770000,1800.000000,5.000000,850.400000,35.27000,7.005000,20.080000,250.000000,62.170000,3.000000

In [490]:
df_master = pd.read_csv("/Applications/python/nutristeppe/data/Final-Master_updated.csv")

/var/folders/1v/01d_s44n27b5nmlgynf1jxd40000gp/T/ipykernel_10777/2997105010.py:1: DtypeWarning: Columns (0,1,2,10,15,30,37,44,60,154,155,156,158,159,160) have mixed types. Specify dtype option on import or set low_memory=False.
  df_master = pd.read_csv("/Applications/python/nutristeppe/data/Final-Master_updated.csv")

In [491]:
df_master[df_master['bls_code'] == 'M306400'][['protein', 'fat','carbohydrate']]

       protein      fat  carbohydrate
11646  35600.0  25801.0          56.0

In [492]:
df_master.columns

Index(['country_code', 'bls_code', 'name_german', 'name_en', 'name_old_ru',
       'name', 'new_name', 'type', 'weight', '5_category',
       ...
       'Хлебные единицы', 'Поваренная соль всего',
       'Средний размер порции г / порцию', 'Сезонность', 'Селен, мкг',
       'TFA, трансжирные кислоты, г', 'Криптоксантин, мкг', 'Лютеин, мкг',
       'Ликопин, мкг', 'Unnamed: 165'],
      dtype='object', length=166)

In [493]:
df.columns

Index(['availability_type', 'carbohydrate', 'cfv', 'dish_category_code',
       'dish_category_id', 'fat', 'fiber', 'fvnl', 'index_health',
       'ingredients', 'kilocalories', 'name', 'pfs_unit', 'protein',
       'quality_requirements', 'salt_total_mg', 'saturated_fat_mg',
       'serving_method', 'serving_size_g', 'steps', 'sugar_mg', 'techcard',
       'type'],
      dtype='object')

In [494]:
df_master=df_master.rename(columns={"5_category": "availability_type"})

In [495]:
# 1. Приводим все колонки в мастере к нижнему регистру и убираем пробелы
df_master.columns = df_master.columns.str.lower().str.strip()

# 2. Твой список (тоже в нижнем регистре)
needed_cols = [
    'bls_code', 'carbohydrate', 'cfv', 'dish_category_id', 'fat', 
    'fiber', 'fvnl', 'index_health', 'ingredients', 'kilocalories', 
    'name', 'pfs_unit', 'protein', 'quality_requirements', 
    'salt_total_mg', 'saturated_fat_mg', 'serving_method', 
    'serving_size_g', 'steps', 'sugar_mg', 'techcard'
]

# 3. ПРОВЕРКА: берем только те колонки, которые РЕАЛЬНО есть в мастере
# Чтобы не вылетал KeyError
actual_cols = [col for col in needed_cols if col in df_master.columns]

print(f"Найдено колонок: {len(actual_cols)} из {len(needed_cols)}")
if len(actual_cols) < len(needed_cols):
    missing = set(needed_cols) - set(actual_cols)
    print(f"ВНИМАНИЕ: Этих колонок нет в мастере: {missing}")

# 4. Теперь создаем обрезанный мастер без ошибок
df_master_limited = df_master[actual_cols].copy()
if 'protein' in df_master_limited.columns:
    # Приводим к числу на случай, если там строки, и делим
    df_master_limited['protein'] = pd.to_numeric(df_master_limited['protein'], errors='coerce') / 1000
if 'protein' in df_master_limited.columns:
    df_master_limited['fat'] = pd.to_numeric(df_master_limited['fat'], errors='coerce') / 1000
if 'protein' in df_master_limited.columns:
    df_master_limited['carbohydrate'] = pd.to_numeric(df_master_limited['carbohydrate'], errors='coerce') / 1000
# 5. Дальше стандартный код (приведение bls_code к строке и объединение)
df_final['bls_code'] = df_final['bls_code'].astype(str).str.strip()
df_master_limited['bls_code'] = df_master_limited['bls_code'].astype(str).str.strip()

df_final.set_index('bls_code', inplace=True)
df_master_limited.set_index('bls_code', inplace=True)

df_final = df_final.combine_first(df_master_limited).loc[df_final.index].reset_index()

Найдено колонок: 6 из 21
ВНИМАНИЕ: Этих колонок нет в мастере: {'ingredients', 'techcard', 'steps', 'quality_requirements', 'kilocalories', 'fvnl', 'sugar_mg', 'serving_method', 'cfv', 'dish_category_id', 'salt_total_mg', 'saturated_fat_mg', 'pfs_unit', 'serving_size_g', 'index_health'}

In [496]:
df_final

,bls_code,availability_type,carbohydrate,cfv,dish_category_code,dish_category_id,fat,fiber,fvnl,index_health,...,protein,quality_requirements,salt_total_mg,saturated_fat_mg,serving_method,serving_size_g,steps,sugar_mg,techcard,type
0,11-1000,2.0,0.00,0.0,VEG01,58.0,0.000,NaN,0.0,0.00,...,0.000,NaN,NaN,NaN,NaN,250.0,NaN,NaN,NaN,2.0
1,11-1006,1.0,53.16,0.0,DGH0201,16.0,3.709,2.505,0.0,0.00,...,7.905,"Булочки должны быть мягкими, с золотистой коро...",0.303,0.301,"Подавать теплые, при температуре 60-70°C.",100.0,"Смешать муку, сахар, соль и дрожжи. Постепенно...",3.61,"Смешать муку, сахар, соль и дрожжи. Постепенно...",2.0
2,11-1011,2.0,0.00,0.0,DGH05,20.0,0.000,NaN,0.0,0.00,...,0.000,NaN,NaN,NaN,NaN,250.0,NaN,NaN,NaN,2.0
3,11-1012,2.0,32.64,0.0,DGH05,20.0,3.340,1425.000,0.0,0.00,...,10.170,"Внешний вид: золотистая корочка, равномерно ра...",NaN,NaN,"Пиццу подают горячей, нарезанной на порционные...",250.0,Пшеничную муку смешивают с сухими дрожжами и ч...,NaN,NaN,2.0
4,11-1013,2.0,0.00,0.0,DGH05,20.0,0.000,2500.000,0.0,0.00,...,0.000,NaN,NaN,NaN,NaN,250.0,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6169,Y993340,2.0,0.00,0.0,DES02,40.0,0.000,130.000,0.0,0.00,...,0.000,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,2.0
6170,Y993440,2.0,0.00,0.0,DES02,40.0,0.000,1868.000,19.2,0.25,...,0.000,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,2.0
6171,Y995140,1.0,20.04,0.0,DES02,40.0,0.232,2.240,0.0,2.50,...,0.406,"Внешний вид: золотистая корочка, дольки мягкие...",0.002,0.031,Подают теплой с шариком ванильного мороженого ...,90.0,Помыть и очистить груши от кожуры. Разрезать п...,18.35,Помыть и очистить груши от кожуры. Разрезать п...,2.0
6172,Y999242,2.0,0.00,0.0,DES02,40.0,0.000,985.000,20.0,0.75,...,0.000,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,2.0
6173,n420100,2.0,0.00,0.0,BEV07,27.0,0.000,0.000,0.0,3.50,...,0.000,NaN,NaN,NaN,NaN,200.0,NaN,NaN,NaN,2.0

In [497]:
df_final.describe()

,availability_type,carbohydrate,cfv,dish_category_id,fat,fiber,fvnl,index_health,kilocalories,protein,salt_total_mg,saturated_fat_mg,serving_size_g,sugar_mg,type
count,6174.000000,6171.000000,5712.000000,5687.000000,6171.000000,5938.000000,5712.000000,5712.000000,5712.000000,6171.000000,2600.000000,2600.000000,5687.000000,2600.000000,6174.000000
mean,1.465339,10.441705,21.813136,30.152629,4.167291,925.265292,46.591999,2.148372,174.583365,5.328839,0.355501,2.173399,143.039388,2.528415,2.067865
std,0.498838,17.061870,89.181991,17.613675,7.138252,1889.607440,133.439805,1.656127,109.648762,6.407401,0.280308,2.770288,63.306060,3.863552,0.251535
min,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,2.000000
25%,1.000000,0.000000,0.000000,16.000000,0.000000,0.762000,0.000000,0.000000,92.762500,0.000000,0.301000,0.364750,100.000000,0.644750,2.000000
50%,1.000000,1.130000,0.000000,29.000000,1.160000,4.687000,3.000000,2.250000,153.800000,2.350000,0.333000,1.022000,150.000000,1.284000,2.000000
75%,2.000000,13.110000,2.500000,48.000000,5.748500,1200.000000,45.500000,3.500000,241.825000,9.344500,0.402000,2.948500,200.000000,2.564250,2.000000
max,2.000000,91.400000,1800.000000,62.000000,93.840000,37044.000000,1800.000000,5.000000,850.400000,35.600000,7.005000,20.080000,250.000000,62.170000,3.000000

In [498]:
df_final.to_csv("24March.csv", index=False)

In [499]:
df_sorted = df_final.sort_values(by='protein', ascending=False)
df_sorted['name']

3890           Сыр Пармезан  30% жирности
3710                    Тыквенные семечки
1221         Жареные кальмары в панировке
3891            Сыр Пармезан 40% жирности
3892            Сыр Пармезан 45% жирности
                      ...
2597     Листья колбасы, жареные с маслом
6173                     Растворимый кофе
114             Мягкая пшеничная тортилья
682     Белый соус на обезжиренном молоке
1736                        Томатный соус
Name: name, Length: 6174, dtype: object